version: "3.8"
services:
    
    reverse-proxy:
        container_name: reverse-proxy
        build: reverse-proxy/.
        ports:
            - 8080:8080
        volumes:
            - ./reverse-proxy/src/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse-proxy/src/sites-available:/etc/nginx/sites-enabled
            
    greeter-alice:
        container_name: greeter-alice
        build: greeter/.
        environment:
            NAME: Alice

    greeter-bob:
        container_name: greeter-bob
        build: greeter/.
        environment:
            NAME: Bob