name: Docker Compose Build

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build via Docker Compose
        run: docker-compose build --no-cache
        working-directory: ./src/
